core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import include, path
from django.views.generic.base import RedirectView

from core.views import (
    robots_txt,
    bad_request_error_400,
    forbidden_error_403,
    page_not_found_view_404,
    internal_error_500,
)

from .sitemaps import CategorySitemap, ProductSitemap, StaticSitemap

sitemaps = {
    "products": ProductSitemap,
    "static": StaticSitemap,
    "categories": CategorySitemap,
}


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("home.urls", namespace="home")),
    path("dashboard/", include("profiles.urls")),
    path("store/", include("store.urls")),
    path("basket/", include("basket.urls")),
    path("checkout/", include("checkout.urls")),
    path("product/", include("products.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("robots.txt", robots_txt),
    path(
        "favicon.ico",
        RedirectView.as_view(
            url=staticfiles_storage.url("webmanifest/favicons/favicon.ico")
        ),
    ),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )


handler400 = "core.views.bad_request_error_400"
handler403 = "core.views.forbidden_error_403"
handler404 = "core.views.page_not_found_view_404"
handler500 = "core.views.internal_error_500"

home/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="home"),
    path("contact-us", views.ContactUs.as_view(), name="contact-us"),
    path(
        "documents/privacy-policy",
        TemplateView.as_view(
            template_name="home/pages/privacy-policy.html"
        ),
        name="privacy-policy",
    ),
    path(
        "documents/terms-of-service-policy",
        TemplateView.as_view(
            template_name="home/pages/terms-of-service-policy.html"
        ),
        name="terms-of-service-policy",
    ),
    path(
        "documents/returns-policy",
        TemplateView.as_view(
            template_name="home/pages/returns-policy.html"
        ),
        name="returns-policy",
    ),
    path(
        "documents/disclaimer-policy",
        TemplateView.as_view(
            template_name="home/pages/disclaimer-policy.html"
        ),
        name="disclaimer-policy",
    ),
    path(
        "documents/shipping-policy",
        TemplateView.as_view(
            template_name="home/pages/shipping-policy.html"
        ),
        name="shipping-policy",
    ),
    path(
        "documents/cookie-policy",
        TemplateView.as_view(
            template_name="home/pages/cookie-policy.html"
        ),
        name="cookie-policy",
    ),
]

templates/base/components/account_and_basket_bar.html
<!-- account_and_basket_bar.html -->
<header class="container-fluid d-none d-md-block">
	<div id="topnav" class="row bg-white pt-lg-2 fixed-top mb-1 d-print-none">
		<div id="brand-logo"
			class="col-12 col-md-4 col-lg-4 my-auto py-1 py-lg-0 text-center text-lg-left">
			<a href="{% url 'home:home' %}" class="nav-link main-logo-link">
				<h4 class="text-black my-0 d-print-inline">
					<span class="logo-font-lkm fs-3">LKM </span><span
						class="logo-font-creations fs-3">Creations</span>
				</h4>
			</a>
		</div>
		<div id="search-box" class="col-md-3 col-lg-4 my-auto py-1 py-lg-0">
			{% include "base/components/search.html" %}
		</div>
		<div id="login-out-register-account"
			class="col-12 col-md-5 col-lg-4 my-auto py-1 d-none d-md-block">
			<ul id="login-out-register-account-menu"
				class="list-inline list-unstyled text-center text-lg-right my-0">
				{% if request.user.is_authenticated %}
				<li class="list-inline-item">
					<a class="nav-link text-primary-darkest nav-svg"
						href="{% url "dashboard" %}" id="account-button"
						data-toggle="dropdown" aria-haspopup="true"
						aria-expanded="false">
						<div class="text-center">
							<div>
								<svg xmlns="http://www.w3.org/2000/svg"
									width="32" height="32" fill="currentColor"
									viewBox="0 0 16 16">
									<path fill-rule="evenodd"
										d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z">
									</path>
								</svg>
							</div>
							<p class="my-0 small">My Account</p>
						</div>
					</a>
				</li>
				<li id="signout-button" class="list-inline-item">
					<a class="nav-link text-primary-darkest nav-svg" href="#"
						role="button" data-bs-toggle="modal"
						data-bs-target="#logoutModal" aria-expanded="false">
						<div class="text-center">
							<div>
								<svg xmlns="http://www.w3.org/2000/svg"
									width="32" height="32" fill="currentColor"
									viewBox="0 0 16 16">
									<path xmlns="http://www.w3.org/2000/svg"
										fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1
										.5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5
										2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0
										1.5-1.5v-2a.5.5 0 0 0-1 0v2z">
									</path>
									<path xmlns="http://www.w3.org/2000/svg"
										fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293
										7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z">
									</path>
								</svg>
							</div>
							<p class="fs-6 fw-semibold">
								Logout
							</p>
						</div>
					</a>
				</li>
				{% else %}
				<li id="register-button" class="list-inline-item">
					<a class="nav-link text-primary-darkest nav-svg"
						href="/accounts/signup" role="button"
						aria-expanded="false">
						<div class="text-center">
							<div>
								<svg xmlns="http://www.w3.org/2000/svg"
									width="32" height="32" fill="currentColor"
									viewBox="0 0 16 16">
									<path fill-rule="evenodd" d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0
										0 0 0 6z">
									</path>
								</svg>
							</div>
							<p class="fs-6 fw-semibold">
								Register
							</p>
						</div>
					</a>
				</li>
				<li id="signin-button" class="list-inline-item">
					<!-- sign-out-confirmation-modal -->
					<!-- Button trigger modal -->
					<a class="nav-link text-primary-darkest nav-svg" href="#"
						role="button" data-bs-toggle="modal"
						data-bs-target="#logInModal" aria-expanded="false">
						<div class="text-center">
							<div><svg xmlns="http://www.w3.org/2000/svg"
									width="32" height="32" fill="currentColor"
									viewBox="0 0 16 16">
									<path xmlns="http://www.w3.org/2000/svg"
										fill-rule="evenodd"
										d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0v-2z">
									</path>
									<path xmlns="http://www.w3.org/2000/svg"
										fill-rule="evenodd"
										d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z">
									</path>
								</svg>
							</div>
							<p class="fs-6 fw-semibold">
								Sign In
							</p>
						</div>
					</a>
				</li>
				{% endif %}
				<li id="basket-button"
					class="list-inline-item text-black text-decoration-none">
					<a href="{% url "summary" %}" class="{% if basket_items %}
		 font-weight-bold {% endif %} nav-link text-primary-darkest nav-svg
		 text-decoration-none" role="button">
						<div class="text-center">
							<div class="d-inline-flex">
								{% if total_quantity is 0 %}
								<span id="basket_quantity-mobile"
									class="small text-muted">
								</span>
								<svg xmlns="http://www.w3.org/2000/svg"
									width="32" height="32" fill="currentColor"
									viewBox="0 0 16 16">
									<path xmlns="http://www.w3.org/2000/svg"
										d="M5.757 1.071a.5.5 0 0 1 .172.686L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15a1 1 0 0 1 1 1v1a1 1 0 0 1-1 1v4.5a2.5 2.5 0 0 1-2.5 2.5h-9A2.5 2.5 0 0 1 1 13.5V9a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h1.217L5.07 1.243a.5.5 0 0 1 .686-.172zM2 9v4.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V9H2zM1 7v1h14V7H1zm3 3a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 4 10zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 6 10zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 8 10zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 1 .5-.5zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 1 .5-.5z">
									</path>
								</svg>
								{% else %}


								<span class="fa-stack nav-svg"
									data-count="{{ total_quantity }}">
									<svg xmlns="http://www.w3.org/2000/svg"
										width="32" height="32"
										fill="currentColor" viewBox="0 0 16 16"
										class="fa-stack">
										<path
											xmlns="http://www.w3.org/2000/svg"
											d="M5.757 1.071a.5.5 0 0 1 .172.686L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15a1 1 0 0 1 1 1v1a1 1 0 0 1-1 1v4.5a2.5 2.5 0 0 1-2.5 2.5h-9A2.5 2.5 0 0 1 1 13.5V9a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h1.217L5.07 1.243a.5.5 0 0 1 .686-.172zM2 9v4.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V9H2zM1 7v1h14V7H1zm3 3a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 4 10zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 6 10zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 8 10zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 1 .5-.5zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 1 .5-.5z">
										</path>
									</svg>
								</span>


								{% endif %}
							</div>
							<p class="fs-6 fw-semibold">
								{% if total_quantity is not 0 %}
								£<span
									id="basket_subtotal-mobile">{{ subtotal | floatformat:2 }}</span>
								{% else %}
								<span id="basket_subtotal-mobile">Basket</span>
								{% endif %}
							</p>
						</div>
					</a>
				</li>
			</ul>
		</div>
		{% include "base/components/navbar.html" %}
	</div>
</header>
<!-- end of account_and_basket_bar.html -->

templates/base/components/navbar.html
{% load active_link_tags %}
<!-- navbar.html -->
<nav class="navbar navbar-expand-md navbar-light bg-primary-light rounded d-none d-md-block d-print-none"
	aria-label="Shop Navigation Bar">
	<div class="container-fluid justify-content-md-center" id="shopNavbar">
		<ul class="navbar-nav">
			<li class="nav-item">
				<a class="nav-link {% if '/sale' in request.path %}active{% endif %}"
					{% if '/sale' in request.path %}aria-current="page"
					{% endif %} href="{% url 'sale' %}">Sale Items</a>
			</li>
			<li class="nav-item">
				<a class="nav-link {% if '/products' in request.path %}active{% endif %}"
					{% if '/products' in request.path %}aria-current="page"
					{% endif %} href="{% url 'products' %}">All
					Products</a>
			</li>
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle {% if '/category/' in request.path %}active{% endif %}"
					{% if '/category/' in request.path %}aria-current="page"
					{% endif %} href="#" id="dropdown"
					data-bs-toggle="dropdown" aria-expanded="false">Shop by
					Category</a>
				<ul class="dropdown-menu" aria-labelledby="dropdown">
					{% for category in categories %}
					<li>
						<a class="dropdown-item"
							href="/store/category/{{ category.slug }}">
							{{ category.name|title }}'s</a>
					</li>
					{% endfor %}
				</ul>
			</li>
			<li class="nav-item">
				<a class="nav-link {% if '/contact-us' in request.path %}active{% endif %}"
					{% if '/contact-us' in request.path %}aria-current="page"
					{% endif %} href="{% url 'home:contact-us' %}">Contact
					Us</a>
			</li>
			<li class="nav-item">
				<!--Newsletter Signup -modal -->
				<!-- Button trigger modal -->
				<a class="nav-link ms-3" href="#" role="button"
					data-bs-toggle="modal"
					data-bs-target="#NewsletterSignupModal"
					aria-expanded="false">
					<svg xmlns="http://www.w3.org/2000/svg" width="28"
						height="28" fill="currentColor" viewBox="0 0 16 16">
						<path fill-rule="evenodd"
							d="M2 2a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2H2ZM1 4a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V4Zm7.5.5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7ZM2 5.5a.5.5 0 0 1 .5-.5H6a.5.5 0 0 1 0 1H2.5a.5.5 0 0 1-.5-.5Zm0 2a.5.5 0 0 1 .5-.5H6a.5.5 0 0 1 0 1H2.5a.5.5 0 0 1-.5-.5Zm0 2a.5.5 0 0 1 .5-.5H6a.5.5 0 0 1 0 1H2.5a.5.5 0 0 1-.5-.5ZM10.5 5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3ZM13 8h-2V6h2v2Z">
						</path>
					</svg>
					Newsletter Signup
				</a>
			</li>
		</ul>
		<div class="d-md-none col-10 offset-1 my-auto py-1 py-lg-0">
			{% include "base/components/search.html" %}
		</div>
	</div>
</nav>
<!-- end of navbar.html -->

templates/base/components/navbar_mobile.html
{% load active_link_tags %}
<!-- navbar_mobile.html -->
<nav class="autohide navbar navbar-expand-md navbar-light bg-white px-4 mb-5
	border-bottom d-md-none d-print-none">
	<div id="mobile-dropdown-menu" class="container-fluid">
		<a class="navbar-brand" href="{% url 'home:home' %}">
			<h4 class="text-black my-0">
				<span class="logo-font-lkm">LKM </span><span
					class="logo-font-creations">Creations</span>
			</h4>
		</a>



		{% if total_quantity is not 0 %}
		<a href="{% url "summary" %}" class="text-primary-darkest nav-svg px-0  text-decoration-none
					{% if total_quantity is 0 %}text-info font-weight-bold
					{% endif %} " role="button">

			<div class="row d-flex align-items-center ">
				<div class="col-4">
					<span class="fa-stack nav-svg"
						data-count="{{ total_quantity }}">
						<svg xmlns="http://www.w3.org/2000/svg" width="32"
							height="32" fill="currentColor" viewBox="0 0 16 16"
							class="fa-stack">
							<path xmlns="http://www.w3.org/2000/svg"
								d="M5.757 1.071a.5.5 0 0 1 .172.686L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15a1 1 0 0 1 1 1v1a1 1 0 0 1-1 1v4.5a2.5 2.5 0 0 1-2.5 2.5h-9A2.5 2.5 0 0 1 1 13.5V9a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h1.217L5.07 1.243a.5.5 0 0 1 .686-.172zM2 9v4.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V9H2zM1 7v1h14V7H1zm3 3a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 4 10zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 6 10zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 8 10zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 1 .5-.5zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 1 .5-.5z">
							</path>
						</svg>
					</span>
				</div>

				<div class="col-8 align-items-center  d-below-375-none">
					<div class="">
						<p class="my-auto small lh-1 text-center">
							Total<br>
							£<span
								id="basket_subtotal">{{ subtotal | floatformat:2 }}
							</span>

						</p>
					</div>
				</div>

			</div>
		</a>
		{% endif %}








		<button class="navbar-toggler" data-bs-toggle="collapse"
			data-bs-target="#main_nav" aria-expanded="false"
			aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse justify-content-md-center"
			id="main_nav">
			<ul class="navbar-nav">
				<li class="nav-item">
					<a class="nav-link {% if '/products' in request.path %}active{% endif %}"
						{% if '/products' in request.path %}aria-current="page"
						{% endif %} href="{% url 'products' %}">All
						Products</a>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle {% if '/category/' in request.path %}active
						{% endif %}" href="#" id="dropdown-categorys-mobile"
						data-bs-toggle="dropdown" aria-expanded="false">Shop by
						Category</a>
					<ul class="dropdown-menu">
						{% for category in categories %}
						<li>
							<a class="dropdown-item"
								href="/store/category/{{ category.slug }}">
								{{ category.name|title }}'s</a>
						</li>
						{% endfor %}
					</ul>
				</li>
				<li class="nav-item">
					<a class="nav-link {% if '/sale' in request.path %}active{% endif %}"
						{% if '/sale' in request.path %}aria-current="page"
						{% endif %} href="{% url 'sale' %}">Sale Items</a>
				</li>
				<li class="nav-item">
					<a class="nav-link {% if '/contact-us' in request.path %}active{% endif %}"
						{% if '/contact-us' in request.path %}aria-current="page"
						{% endif %} href="{% url 'home:contact-us' %}">Contact
						Us</a>
				</li>
				<li id="newsletter-signup-button-mobile" class="nav-item">
					<a class="nav-link ms-0 ms-md-3" href="#" role="button"
						data-bs-toggle="modal"
						data-bs-target="#NewsletterSignupModal"
						aria-expanded="false">
						<svg xmlns="http://www.w3.org/2000/svg" width="28"
							height="28" fill="currentColor"
							viewBox="0 0 16 16">
							<path fill-rule="evenodd"
								d="M2 2a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2H2ZM1 4a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V4Zm7.5.5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7ZM2 5.5a.5.5 0 0 1 .5-.5H6a.5.5 0 0 1 0 1H2.5a.5.5 0 0 1-.5-.5Zm0 2a.5.5 0 0 1 .5-.5H6a.5.5 0 0 1 0 1H2.5a.5.5 0 0 1-.5-.5Zm0 2a.5.5 0 0 1 .5-.5H6a.5.5 0 0 1 0 1H2.5a.5.5 0 0 1-.5-.5ZM10.5 5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3ZM13 8h-2V6h2v2Z">
							</path>
						</svg>
						Newsletter Signup
					</a>
				</li>
			</ul>
			<ul class="nav flex-row justify-content-around">
				{% if request.user.is_authenticated %}
				<li id="logout-button-mobile" class="list-inline-item">
					<a class="nav-link text-primary-darkest nav-svg px-0"
						href="#" role="button" data-bs-toggle="modal"
						data-bs-target="#logoutModal" aria-expanded="false">
						<div class="text-center">
							<div>
								<svg xmlns="http://www.w3.org/2000/svg"
									width="24" height="24" fill="currentColor"
									viewBox="0 0 16 16">
									<path xmlns="http://www.w3.org/2000/svg"
										fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1
										.5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5
										2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0
										1.5-1.5v-2a.5.5 0 0 0-1 0v2z">
									</path>
									<path xmlns="http://www.w3.org/2000/svg"
										fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293
										7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z">
									</path>
								</svg>
							</div>
							<p class="fs-6 fw-semibold small">
								Logout
							</p>
						</div>
					</a>
				</li>
				<li class=" list-inline-item">
					<a class="nav-link text-primary-darkest nav-svg px-0"
						href="{% url "dashboard" %}"
						id="my-account-button-mobile" data-toggle="dropdown"
						aria-haspopup="true" aria-expanded="false">
						<div class="text-center">
							<div><svg xmlns="http://www.w3.org/2000/svg"
									width="24" height="24" fill="currentColor"
									viewBox="0 0 16 16">
									<path fill-rule="evenodd"
										d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z">
									</path>
								</svg>
							</div>
							<p class="my-0 small">
								My
								Account</p>
						</div>
					</a>
				</li>
				{% else %}
				<li id="registration-button-mobile" class="list-inline-item">
					<a class="nav-link text-primary-darkest nav-svg px-0"
						href="/accounts/signup" role="button"
						aria-expanded="false">
						<div class="text-center">
							<div>
								<svg xmlns="http://www.w3.org/2000/svg"
									width="24" height="24" fill="currentColor"
									viewBox="0 0 16 16">
									<path fill-rule="evenodd" d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0
										0 0 0 6z">
									</path>
								</svg>
							</div>
							<p class="fs-6 fw-semibold small">
								Register
							</p>
						</div>
					</a>
				</li>
				<li id="login-button-mobile" class="list-inline-item">
					<a class="nav-link text-primary-darkest nav-svg px-0"
						href="#" role="button" data-bs-toggle="modal"
						data-bs-target="#logInModal" aria-expanded="false">
						<div class="text-center">
							<svg xmlns="http://www.w3.org/2000/svg" width="24"
								height="24" fill="currentColor"
								viewBox="0 0 16 16">
								<path xmlns="http://www.w3.org/2000/svg"
									fill-rule="evenodd"
									d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0v-2z">
								</path>
								<path xmlns="http://www.w3.org/2000/svg"
									fill-rule="evenodd"
									d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z">
								</path>
							</svg>
							<p class="fs-6 fw-semibold small">
								Sign In
							</p>
						</div>
					</a>
				</li>
				{% endif %}

			</ul>
			<div class="d-md-none col-10 offset-1 my-auto py-1 py-lg-0">
				{% include "base/components/search.html" %}
			</div>
		</div> <!-- navbar-collapse.// -->
	</div>
	<!-- container-fluid.// -->
</nav>
<!-- end of navbar_mobile.html -->